### PR TITLE
Use OPL-3 soundfont

### LINKED ISSUE #39: Please include the free OPL3 MIDI SoundFont in "/app/share/sounds/sf2"
Hi, everyone,

I was hoping that the Flatpak version of OpenTTD could use this OPL3 sound font - https://github.com/Mindwerks/opl3-soundfont

The package name in Debian is `opl3-soundfont`. And it is released under a CC-BY-SA 4.0 license.

My reasoning is that it sounds a lot better than the standard FluidSynth GM and GS SoundFonts that come with it. There are volume mixing issues with some instruments when using it. And in general, certain parts of the songs when played with the Jukebox sound terrible with the FluidSynth backend, and are often too loud.

I understand that vanilla OpenTTD heavily relies on Timidity+Freepats instead, but I thought a good alternative would be great.

I have also looked at these threads below, so I will reference them:
- https://github.com/OpenTTD/OpenTTD/issues/6873
- https://github.com/OpenTTD/OpenTTD/pull/7522

When I use `flatpak run org.openttd.OpenTTD -m fluidsynth:soundfont=/app/share/sounds/sf2/FluidR3_GM.sf2`, it works just fine.

However, when I try to run `flatpak run org.openttd.OpenTTD -m fluidsynth:soundfont=/usr/share/sounds/sf2/OPL-3_FM_128M.sf2` it returns this error:

```
fluidsynth: error: fluid_sfloader_load(): Failed to open '/usr/share/sounds/sf2/OPL-3_FM_128M.sf2': File does not exist.
fluidsynth: error: Unable to open file '/usr/share/sounds/sf2/OPL-3_FM_128M.sf2'
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/OPL-3_FM_128M.sf2"
Error: Unable to load driver 'fluidsynth'. The error was: Could not open sound font
```

Even when specifying `--filesystem=host` or `--filesystem=/usr/share/sounds/sf2/`, it will still return the exact same error. So for some reason, it won't load.

I even did some research to find out that the mysterious `/app/share/` directory actually points to `/var/lib/flatpak/app/org.openttd.OpenTTD/x86_64/stable/<HASH>/files/share/`, where <HASH> appears to be some sort of checksum, likely SHA-256.

Anyway, when I copied over the `/usr/share/sounds/sf2/OPL-3_FM_128M.sf2` (OPL-3 SoundFont) file to that `/var/lib/flatpak/<...>/share/sounds/sf2/` directory, it still refused to load it at all.

If there is any way anybody knows how to make that work, or can provide a fix for it, please let me know!

The version I am using is OpenTTD 1.10.3 (Flatpak stable repo).

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #39

### CODE REVIEW

**Comment by ghisvail** [comment]
Weird, it's working fine on my machine.
Capture d’écran de 2021-03-31 13-44-01

**Comment by ghisvail** [comment]
I get a few of these in the logs when listening to the music titles:

`fluidsynth: warning: Instrument not found on channel 9 [bank=128 prog=16], substituted [bank=128 prog=0]`

Does it mean this sound font is not exhaustive enough?

**Comment by mrjpaxton** [comment]
> I get a few of these in the logs when listening to the music titles:
> 
> `fluidsynth: warning: Instrument not found on channel 9 [bank=128 prog=16], substituted [bank=128 prog=0]`
> 
> Does it mean this sound font is not exhaustive enough?

The SoundFont has 128 instruments. I took a look with Polyphone editor just to make sure.

The General MIDI standard specifies that it can have 128 program numbers (instruments), which is good, and 16 channels, but it is saying channel 9 for program 16 is missing. But I have it visible in Polyphone as "016_09", so I don't get it... Which version is your OPL3-SoundFont?

Anyway, if I recall, if a channel is missing, it will be substituted for another sample, which is fine. Normally each channel will correspond to each octave in the sound from 1 to 10, while channel 11-16 is reserved for additional instruments. Each channel may be pitch-shifted according to the semitone/tone in the instrument... I think.

## References:
- https://www.polyphone-soundfonts.com
- https://en.wikipedia.org/wiki/General_MIDI

**Comment by ghisvail** [comment]
> Which version is your OPL3-SoundFont?

Version 1.0 published on [GitHub releases](https://github.com/Mindwerks/opl3-soundfont/releases/download/1.0/OPL-3_FM_128M.sf2).

> Anyway, if I recall, if a channel is missing, it will be substituted for another sample, which is fine.

I'll take your word for it. May be worth checking whether this also happens with the other sound font (FluidR3_GM.sf2) nonetheless.

**Comment by ghisvail** [comment]
This PR is now rebased on top of version 1.11.0 final.

**Comment by ghisvail** [comment]
> fluidsynth: warning: Instrument not found on channel 9 [bank=128 prog=16], substituted [bank=128 prog=0]

Btw, I am not getting this error with neither FluidR3 nor MuseScore_General.

**Comment by ghisvail** [comment]
Closed in favor of #44

**Pull request closed without merging**
